#ifndef __AUDIO_H__
#define __AUDIO_H__
#include "gfc_audio.h"
	GFC_Sound* TitleScreen;
    GFC_Sound* ArticunoLevel;
    GFC_Sound* GameOver;
    GFC_Sound* PasswordScreen;
    GFC_Sound* PikachuLevel;
    GFC_Sound* ZubatLevel;
    GFC_Sound* StageSelect;
    GFC_Sound* ArticunoAttack;
    GFC_Sound* BetamonJump;
    GFC_Sound* BossHit;
    GFC_Sound* EnemyHit;
    GFC_Sound* EnemyShoot;
    GFC_Sound* EtemonProjectile;
    GFC_Sound* FireballAttack;
    GFC_Sound* GabumonPunch;
    GFC_Sound* GabumonSpin;
    GFC_Sound* GallantmonProjectile;
    GFC_Sound* GuilmonClaw;
    GFC_Sound* LevelComplete;
    GFC_Sound* PauseMenu;
    GFC_Sound* PikachuAttack;
    GFC_Sound* PlayerHit;
    GFC_Sound* PlayerDefeat;
    GFC_Sound* PlayerRestore;
    GFC_Sound* ProjectileHit;
    GFC_Sound* WarGreymonProjectile;
    GFC_Sound* ZubatAttack;
    GFC_Sound* No;
    GFC_Sound* Editor;
#endif
